services:
  backend:
    extends:
      file: todo-backend/docker-compose.yml
      service: server
  mongo:
    extends:
      file: todo-backend/docker-compose.yml
      service: mongo
  redis:
    extends:
      file: todo-backend/docker-compose.yml
      service: redis
  frontend:
     extends:
      file: todo-frontend/docker-compose.yml
      service: app
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - backend
      - frontend

volumes:
  mongo_data:
